### ISSUE TITLE
Ogar 3 skins

### ISSUE THREAD

**Issue by Anon10104** [Faris90/Ogar3#17]
the skins wont load i would appreciate if you fixed this i know the old version had a similar issue ![image](https://user-images.githubusercontent.com/94852759/233645239-be45c167-b636-4511-bb22-46fd72c2f108.png)

**Comment by Anon10104-2** [comment]
as far as i have found relit is doing weird  things to the checkdir.php bc replit is running it as node.js (i mean as far as ik)

**Comment by Faris90** [comment]
I'll fix that

**Comment by Faris90** [comment]
also you seem to have a problem on repl @Anon10104 right?

**Comment by Anon10104** [comment]
yes

**Comment by Faris90** [comment]
Well I am going to need to rewrite the code

**Comment by Anon10104** [comment]
Yeah I figured but thank you for replying and letting me know that you're at least working on it

**Comment by Faris90** [comment]
Can I see?

**Comment by Anon10104** [comment]
Can you see what ?

**Comment by Anon10104** [comment]
Also fun fact not super important or anything but a friend of mine was messing around with the ogar site that I'm hosting and realized with Google Dev tools he could connect to the web socket multiple times and just flood the server just a heads up

**Comment by Faris90** [comment]
The repl

**Comment by Anon10104** [comment]
https://anon10104.gq/ (the site) 
https://replit.com/@BraxtonSS/Ogar3-1 (not my account is a freinds from school )

**Comment by Faris90** [comment]
I sorta fixed it(skins gallery will be also worked on), all you need to do is to upload in skins folder like for example: coolskin.png and then add it to skinList.txt in client by doge,example,**coolskin**
![image](https://user-images.githubusercontent.com/24720470/235265302-c17ce6e3-d743-4164-b376-0708174e1a2e.png)

**Comment by Anon10104** [comment]
k thx!

**Comment by Anon10104** [comment]
didnt work? am i missing something

**Comment by Faris90** [comment]
Silly me forgot to push origin :P

**Comment by Anon10104** [comment]
thanks :) 👍
