### ISSUE TITLE
Replit Free Hosting

### ISSUE THREAD

**Issue by Anon10104** [Faris90/Ogar3#24]
Replit no longer has free hosting and has affected your tracker do you know of any free other hosting options for it or make it work with Cloudflare pages perhaps.

**Comment by Faris90** [comment]
Replit fell off...

**Comment by hopperelec** [comment]
I'd recommend using Vercel- it's free (for hobbyists) and automatically syncs with the GitHub repo. It also hosts every commit at the same time, like GitHub Pages except not just static, so you can look at old versions easily. You also don't need to "Run" it like on replit, it's just kinda always running (but it's serverless, so code only runs when a client is connected).

(sorry if this sounds like I work for them or are sponsored by them, I promise I don't and am not)

**Comment by Faris90** [comment]
Ok

**Comment by Faris90** [comment]
@HopperElec should I put in a vite.config.json?

**Comment by Anon10104-2** [comment]
might just be me when trying to host on vercel i get this and it never deploys
![image](https://github.com/Faris90/Ogar3/assets/58088206/53ab380c-7541-42bf-ba86-4a3f99aa53cf)

**Comment by hopperelec** [comment]
Since your Javascript is "pre-compiles" (as in, it is already in an executable format, I don't think you need to build anything and `vercel-build` isn't necessary. The "Building" step should only be cloning the repo and then installing npm packages. Your app should only start running in the "Deployment" step but right now it's doing it in the build step and of course your app is supposed to stay online meaning the build step is getting stuck (I'm surprised it doesn't time out)

**Comment by Anon10104-2** [comment]
so how would you recommend do it (im sorry i dont use vercel often)

**Comment by hopperelec** [comment]
I only started using it recently and only for Svelte which handles Vercel automatically. But, I'd imagine you could just remove the `vercel-build` npm script, or fail in that you can configure the build command in the dashboard

**Comment by Faris90** [comment]
I am not used to vercel @HopperElec lol

**Comment by Anon10104** [comment]
Faris I found a way of hosting again I'm using render with the free version a little laggy but is usable plus it has auto update so if you update the GitHub repo the page auto deploys here is mine if you would like to try
https://ogar3-llic.onrender.com/

**Comment by Faris90** [comment]
I use it as well

**Comment by Faris90** [comment]
@Anon10104-2 @Anon10104 use render.com
