### ISSUE TITLE
Skins Gallery doesn't work

### ISSUE THREAD

**Issue by cntaylor** [Faris90/Ogar3#4]
I am hosting your server on an AWS server.  This worked out of the box.  Thank you!  (I had spent several hours trying out other servers.  This is the first one that worked 100% for me!)

When I get to the front page, there is "Skins Gallery" button.  When I click on it there is a

Cannot GET /client/gallery/

page.  If I just type in the web address, I get the same error.   Ideas?  I also tried IP/client/gallery/index.php, but it just downloaded the php file.

I saw on another issue you wanted to check out the server.  I have e-mailed you the server's IP address.

**Comment by Faris90** [comment]
oh php is not supported yet

**Comment by cntaylor** [comment]
Makes sense.  Thanks.
