### ISSUE TITLE
Spectator Mode

### ISSUE THREAD

**Issue by ajz123** [Faris90/Ogar3#5]
Can you please provide some directions on how to enable and then use spectator mode. The button is greyed out for me.

**Comment by Faris90** [comment]
oh just change `  <button id="spectateBtn" onclick="spectate(); return false;" disabled
                            class="btn btn-warning btn-spectate btn-needs-server">Spectate
                    </button>`
to
`  <button id="spectateBtn" onclick="spectate(); return false;" 
                            class="btn btn-warning btn-spectate btn-needs-server">Spectate
                    </button>`
